### ISSUE TITLE
Shared Nextflow environment not available.

### ISSUE THREAD

**Issue by n-equals-one** [NBISweden/assembly-project-template#13]
The shared Nextflow environment referred to in: 
analyses/01_assembly-workflow_initial-run_rackham/run_nextflow.sh

is no longer available.  
Do we need to point it somewhere else or simply just create a new environment?

**Comment by mahesh-panchal** [comment]
What happened to the allocation? 

Either:
Make a new environment and make a PR to the correct the path in the template.
Or:
Comment out the environment setup in the `run_nextflow.sh` and load Nextflow from your own conda environment or from modules.  

We should make an `envs` folder with the conda definition of the environment.
